todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

todoapp/todolist/urls.py
from django.urls import path
from todolist import views

app_name='todolist'
urlpatterns = [
    # ex: /todo/
    path('', views.IndexView.as_view(), name='IndexView'),

    # ex: /todo/1/
    path('<int:pk>/', views.ListDetailView.as_view(), name='ListDetailView'),

    # ex: /todo/1/submit
    path('<int:todolist_id>/submit/', views.submitForm, name='submitForm'),

    # ex: /todo/1/result/
    path('<int:todolist_id>/result/', views.result, name='result'),
    ]


#{% url todolist:submitForm todolist.id %}

todoapp/todolist/models.py
from django.db import models
import datetime

# Create your models here.

class TodoList(models.Model):
    title = models.CharField(max_length=100)
    completed = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class TodoItem(models.Model):
    todolist = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    date_created= models.DateTimeField('created on')
    due_date = models.DateTimeField('date due')


    def __str__(self):
        return self.name

todoapp/todolist/views.py
from django.shortcuts import render
from django.views import generic
from .models import TodoItem, TodoList
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.

class IndexView(generic.ListView):
    model = TodoList
    template_name = 'todolist/index.html'


class ListDetailView(generic.DetailView):
    model = TodoList
    template_name = 'todolist/TodoList_detail.html'



def result(request, todolist_id):
    print(todolist_id)
    todolist = TodoList.objects.get(id=todolist_id)

    return HttpResponse(f"Completed {todolist.completed} item/s from the list ({todolist.title})")




def submitForm(request, todolist_id):
    list_ = request.POST.getlist('checks')
    print(list_)
    todolist = TodoList.objects.get(id=todolist_id)
    todolist.completed = len(list_)
    todolist.save()


    return HttpResponseRedirect(reverse('todolist:result', args=(todolist.id,)))

#reverse('todolist:result', args=(todolist.id,))

todoapp/todolist/templates/todolist/TodoList_detail.html
{% if todolist  %}
    <h1>{{todolist.title}} </h1><br>
    Completed: {{todolist.completed}}
    <hr>


    <form action="{% url 'todolist:submitForm' todolist.id %}" method="POST">
        {% csrf_token %}
        {% for item in todolist.todoitem_set.all %}
        <input type="checkbox" name="checks" value="{{ item.id }}">{{ item.name }}
        <br>
        {% endfor %}
        <input type="submit" value="Submit!">
    </form>
{% endif %}

todoapp/todolist/templates/todolist/index1.html
<h1>Todo Lists:</h1>
{% if object_list %}
<ul>
{%for todoList in object_list %}
 <li><a href="{% url 'todolist:ListDetailView' todoList.id %}"> {{todoList.title }} </a></li>
<hr>
<br>
{%endfor%}
</ul>
{%endif%}